version: '3'
services:
  web:
    restart: always
    build:
      context: .
      dockerfile: deploy/docker/web.Dockerfile
    ports:
    - "80:5000"
    links:
    - redis
    volumes:
    - "/optane/yaraFiles/samples/:/mnt/samples"
    depends_on:
      - "redis"
      - "ursadb"
  daemon:
    restart: always
    build:
      context: .
      dockerfile: deploy/docker/daemon.Dockerfile
    links:
    - redis
    - ursadb
    volumes:
    - "/optane/yaraFiles/samples/:/mnt/samples"
    depends_on:
      - "redis"
      - "ursadb"
    environment:
    - "MQUERY_BACKEND=tcp://ursadb:9281"
  ursadb:
    restart: always
    build:
      context: ursadb/
      dockerfile: Dockerfile
    ports:
    - "127.0.0.1:9281:9281"
    volumes:
    - "/optane/yaraFiles/samples/:/mnt/samples"
    - "/optane/yaraFiles/ursadb-indexes/general/:/var/lib/ursadb"
  redis:
    restart: always
    image: redis
